// =============================================================
// Ace Manager — Niles North Course Catalog (static reference)
// =============================================================
// 319 courses across 31 departments, pre-classified academic vs
// non-academic. Source: IEP Builder v7.1 D219_COURSE_GROUPS.
// Regenerate yearly if the NN course catalog changes.
// =============================================================

window.aceCourseCatalog = [
  { name: 'AP African American Studies', code: null, department: 'Interdepartmental', is_academic: true },
  { name: 'AP Seminar', code: null, department: 'Interdepartmental', is_academic: true },
  { name: 'AP Research', code: null, department: 'Interdepartmental', is_academic: true },
  { name: 'The Science of Well-being', code: null, department: 'Interdepartmental', is_academic: true },
  { name: 'AVID 9', code: 'AV1A01', department: 'AVID', is_academic: false },
  { name: 'AVID 10', code: 'AV1A02', department: 'AVID', is_academic: false },
  { name: 'AVID 11 Honors', code: 'AV1A13', department: 'AVID', is_academic: false },
  { name: 'AVID 12 Honors', code: 'AV1A14', department: 'AVID', is_academic: false },
  { name: 'Automotive Technology 1', code: null, department: 'Automotive Technology', is_academic: false },
  { name: 'Automotive Technology 2', code: null, department: 'Automotive Technology', is_academic: false },
  { name: 'Automotive Technology 3', code: null, department: 'Automotive Technology', is_academic: false },
  { name: 'Automotive Technology 4', code: null, department: 'Automotive Technology', is_academic: false },
  { name: 'Business & Technology 1', code: 'BUSB09', department: 'Business Education', is_academic: true },
  { name: 'Business & Technology 2', code: 'BUSB10', department: 'Business Education', is_academic: true },
  { name: 'Financial Literacy + Consumer Education', code: 'BUSC01', department: 'Business Education', is_academic: true },
  { name: 'Investing and Finance', code: 'BUSI03', department: 'Business Education', is_academic: true },
  { name: 'Marketing', code: 'BUSS01', department: 'Business Education', is_academic: true },
  { name: 'Business Incubator Honors', code: 'BUYB12', department: 'Business Education', is_academic: true },
  { name: 'Business Strategies & Entrepreneurship Honors', code: 'BUYB11', department: 'Business Education', is_academic: true },
  { name: 'College Business / Dual Credit', code: 'BUYB14', department: 'Business Education', is_academic: true },
  { name: 'Financial College Accounting AP', code: 'BUYA05', department: 'Business Education', is_academic: true },
  { name: 'Managerial College Accounting AP', code: 'BUYA07', department: 'Business Education', is_academic: true },
  { name: 'Work Study', code: 'CVYC01', department: 'Business Education', is_academic: false },
  { name: 'Introduction to Computer Science', code: 'ITSC01', department: 'Computer Science', is_academic: true },
  { name: 'Artificial Intelligence', code: null, department: 'Computer Science', is_academic: true },
  { name: 'AP Cybersecurity 1: Networking Fundamentals / Dual Credit', code: 'ITYS07', department: 'Computer Science', is_academic: true },
  { name: 'AP Computer Science Principles', code: 'ITYC03', department: 'Computer Science', is_academic: true },
  { name: 'AP Computer Science A', code: 'ITYC05', department: 'Computer Science', is_academic: true },
  { name: 'Advanced App Development AP', code: 'ITYA07', department: 'Computer Science', is_academic: true },
  { name: 'Computer Repair & Networking', code: 'ETYC01', department: 'Computer Science', is_academic: true },
  { name: 'Introduction to Engineering Design IED-PLTW AP / Dual Credit', code: 'ETYE03', department: 'Engineering', is_academic: true },
  { name: 'Introduction to Engineering Design — Women in Engineering AP', code: 'ETYE03-W', department: 'Engineering', is_academic: true },
  { name: 'MakerStudio / Dual Credit', code: 'ETSM05', department: 'Engineering', is_academic: true },
  { name: 'Principles of Engineering POE-PLTW AP / Dual Credit', code: 'ETYE01', department: 'Engineering', is_academic: true },
  { name: 'Civil Engineering & Architecture CEA-PLTW AP / Dual Credit', code: 'ETYE09', department: 'Engineering', is_academic: true },
  { name: 'CNC Programming & Machining Technology / Dual Credit', code: 'ETSM03', department: 'Engineering', is_academic: true },
  { name: 'Computer Integrated Manufacturing CIM-PLTW AP / Dual Credit', code: 'ETYE07', department: 'Engineering', is_academic: true },
  { name: 'Digital Electronics DE-PLTW AP / Dual Credit', code: 'ETYE05', department: 'Engineering', is_academic: true },
  { name: 'Welding & Metal Fabrication / Dual Credit', code: 'ETSM01', department: 'Engineering', is_academic: true },
  { name: 'Advanced Welding & Metal Fabrication / Dual Credit', code: 'ETSM02', department: 'Engineering', is_academic: true },
  { name: 'Building Trades', code: null, department: 'Engineering', is_academic: true },
  { name: 'Engineering Design & Development EDD-PLTW AP', code: 'ETYE11', department: 'Engineering', is_academic: true },
  { name: 'Freshman English with Reading', code: 'ENYF19', department: 'English', is_academic: true },
  { name: 'Freshman English', code: 'ENYF03', department: 'English', is_academic: true },
  { name: 'Sophomore English', code: 'ENYS03', department: 'English', is_academic: true },
  { name: 'Integrated Reading 3-4', code: 'RDYR39', department: 'English', is_academic: true },
  { name: 'American Studies — Literature and Composition', code: 'ENYJ09', department: 'English', is_academic: true },
  { name: 'American Literature and Composition', code: 'ENYJ15', department: 'English', is_academic: true },
  { name: 'AP English Language and Composition', code: 'EN7J13', department: 'English', is_academic: true },
  { name: 'Senior English: Black and African Stories', code: 'ENSA03', department: 'English', is_academic: true },
  { name: 'Senior English: College Writing and Research / Dual Credit', code: 'ENYL19', department: 'English', is_academic: true },
  { name: 'Senior English: Literature of Moral Conflict', code: 'ENSC10', department: 'English', is_academic: true },
  { name: 'Senior English: Literature of Peace and Nonviolence', code: 'ENSC20', department: 'English', is_academic: true },
  { name: 'Senior English: Literature of Sports and American Culture', code: 'ENSC30', department: 'English', is_academic: true },
  { name: 'Senior English: Social Justice and Equity', code: 'ENSC40', department: 'English', is_academic: true },
  { name: 'Senior English: Women and Gender Studies in Literature / Dual Credit', code: 'ENSC50', department: 'English', is_academic: true },
  { name: 'Senior English: World Literature', code: 'ENSC60', department: 'English', is_academic: true },
  { name: 'AP English Literature', code: 'ENYL01', department: 'English', is_academic: true },
  { name: 'Creative Writing', code: 'ENSG06', department: 'English', is_academic: true },
  { name: 'English Composition & Rhetoric', code: 'ENSG08', department: 'English', is_academic: true },
  { name: 'Intro to Literacy Comprehension', code: 'RDYR02', department: 'English', is_academic: true },
  { name: 'Journalism', code: 'ENSG03', department: 'English', is_academic: false },
  { name: 'Literacy Applications', code: 'RDYR03', department: 'English', is_academic: true },
  { name: 'Literacy Foundations', code: 'RDYR01', department: 'English', is_academic: true },
  { name: 'Newspaper Production Honors', code: 'ENYG14', department: 'English', is_academic: false },
  { name: 'Public Speaking', code: 'ENSC13', department: 'English', is_academic: true },
  { name: 'Asian American Studies — Literature', code: 'ENSA02', department: 'English', is_academic: true },
  { name: 'Yearbook Production Honors', code: 'EN1G17', department: 'English', is_academic: false },
  { name: 'Bible and Mythology / Dual Credit', code: 'ENSL94', department: 'English', is_academic: true },
  { name: 'Images of Literature', code: 'ENSC07', department: 'English', is_academic: true },
  { name: 'Digital Storytelling', code: 'ENSG09', department: 'English', is_academic: true },
  { name: 'Motion Graphics for Broadcast Journalism', code: 'ENSG15', department: 'English', is_academic: false },
  { name: 'Novice Broadcast Production', code: 'ENST13', department: 'English', is_academic: false },
  { name: 'Honors Broadcast Production', code: 'ENYT14', department: 'English', is_academic: false },
  { name: 'Chefs', code: 'FCSC02', department: 'Family and Consumer Sciences', is_academic: false },
  { name: 'Exploration into Education & Leadership', code: 'FSCE01', department: 'Family and Consumer Sciences', is_academic: false },
  { name: 'Fashion 1', code: 'FCSF01', department: 'Family and Consumer Sciences', is_academic: false },
  { name: 'Fashion 2', code: 'FCSF02', department: 'Family and Consumer Sciences', is_academic: false },
  { name: 'Fashion Studio / Dual Credit', code: 'FCYF03', department: 'Family and Consumer Sciences', is_academic: false },
  { name: 'Gourmet and International Cuisine', code: 'FCSC04', department: 'Family and Consumer Sciences', is_academic: false },
  { name: 'Commercial Foods Workshop', code: 'FCYC06', department: 'Family and Consumer Sciences', is_academic: false },
  { name: 'Early Childhood Education Level 1', code: 'FCYD01', department: 'Family and Consumer Sciences', is_academic: false },
  { name: 'Early Childhood Education Level 2 / Dual Credit', code: 'FCYD03', department: 'Family and Consumer Sciences', is_academic: false },
  { name: 'Beginning Band', code: 'MUYB01', department: 'Music — Band', is_academic: false },
  { name: 'Concert Band', code: 'MUYB03', department: 'Music — Band', is_academic: false },
  { name: 'Jazz Band Early Bird', code: 'MUYB09', department: 'Music — Band', is_academic: false },
  { name: 'Percussion Techniques', code: 'MUYM01', department: 'Music — Band', is_academic: false },
  { name: 'Advanced Percussion Techniques Honors', code: 'MUYM02', department: 'Music — Band', is_academic: false },
  { name: 'Symphonic Band', code: 'MUYB05', department: 'Music — Band', is_academic: false },
  { name: 'Symphonic Wind Ensemble Honors', code: 'MUYB07', department: 'Music — Band', is_academic: false },
  { name: 'Chamber Choir', code: 'MUYC07', department: 'Music — Choir', is_academic: false },
  { name: 'Choraliers', code: 'MUYC01', department: 'Music — Choir', is_academic: false },
  { name: 'Concert Choir', code: 'MUYC03', department: 'Music — Choir', is_academic: false },
  { name: 'Advanced Choir Honors', code: 'MUYC10', department: 'Music — Choir', is_academic: false },
  { name: 'Orchestra Beginning Strings', code: 'MUYS01', department: 'Music — Orchestra', is_academic: false },
  { name: 'Concert Orchestra', code: 'MUYS03', department: 'Music — Orchestra', is_academic: false },
  { name: 'Philharmonic Orchestra', code: 'MUYS09', department: 'Music — Orchestra', is_academic: false },
  { name: 'Symphonic Orchestra Honors', code: 'MUYS05', department: 'Music — Orchestra', is_academic: false },
  { name: 'Arts Appreciation', code: 'DRSA05', department: 'Music — Other', is_academic: false },
  { name: 'Guitar 1', code: 'MUSS07', department: 'Music — Other', is_academic: false },
  { name: 'Guitar 2', code: 'MUSS15', department: 'Music — Other', is_academic: false },
  { name: 'Guitar Ensemble', code: 'MUYS20', department: 'Music — Other', is_academic: false },
  { name: 'Digital Piano 1', code: 'MUSP01', department: 'Music — Other', is_academic: false },
  { name: 'Digital Piano 2', code: 'MUSP02', department: 'Music — Other', is_academic: false },
  { name: 'Electronic Music', code: 'MUST05', department: 'Music — Other', is_academic: false },
  { name: 'Music Theory Honors', code: 'MUYT03', department: 'Music — Other', is_academic: false },
  { name: 'AP Music Theory', code: 'MUYT13', department: 'Music — Other', is_academic: false },
  { name: 'Acting', code: 'DRSA01', department: 'Theatre', is_academic: false },
  { name: 'Stagecraft', code: 'DR0S01', department: 'Theatre', is_academic: false },
  { name: 'Theatre Workshop', code: 'DRST01', department: 'Theatre', is_academic: false },
  { name: 'Advanced Theatre Studio Honors', code: 'DRSA02', department: 'Theatre', is_academic: false },
  { name: 'Directing Honors', code: 'DRSD01', department: 'Theatre', is_academic: false },
  { name: 'Play Production Honors', code: 'DRSP01', department: 'Theatre', is_academic: false },
  { name: 'Art Foundations', code: 'ARSA01', department: 'Visual Arts', is_academic: false },
  { name: 'Ceramics + Sculpture I', code: 'ARSC01', department: 'Visual Arts', is_academic: false },
  { name: 'Ceramics + Sculpture II', code: 'ARSC05', department: 'Visual Arts', is_academic: false },
  { name: 'Digital Photography 1', code: 'ARST03', department: 'Visual Arts', is_academic: false },
  { name: 'Digital Photography 2', code: 'ARST05', department: 'Visual Arts', is_academic: false },
  { name: 'Graphic Design 1', code: 'ARST01', department: 'Visual Arts', is_academic: false },
  { name: 'Painting and Drawing', code: 'ARSA21', department: 'Visual Arts', is_academic: false },
  { name: 'Advanced Studio Art Honors', code: 'ARYA15', department: 'Visual Arts', is_academic: false },
  { name: 'Advanced 2-D Design Honors', code: 'ARYT07', department: 'Visual Arts', is_academic: false },
  { name: 'Advanced 3-D Design', code: null, department: 'Visual Arts', is_academic: false },
  { name: 'AP Studio Art: 3-D Design', code: 'ARYA12', department: 'Visual Arts', is_academic: false },
  { name: 'AP Studio Art: Drawing', code: 'ARYA11', department: 'Visual Arts', is_academic: false },
  { name: 'AP Studio Art: 2-D Design', code: 'ARYT09', department: 'Visual Arts', is_academic: false },
  { name: 'Algebra Essentials', code: 'MAYA02', department: 'Mathematics', is_academic: true },
  { name: 'Algebra Fundamentals ELL', code: 'MAYX01', department: 'Mathematics', is_academic: true },
  { name: 'Algebra 1', code: 'MAYA03', department: 'Mathematics', is_academic: true },
  { name: 'Algebra 1 Extension', code: 'MAYA03-E', department: 'Mathematics', is_academic: true },
  { name: 'Geometry', code: 'MAYG03', department: 'Mathematics', is_academic: true },
  { name: 'Geometry Extension', code: 'MAYG03-E', department: 'Mathematics', is_academic: true },
  { name: 'Geometry Advanced Honors', code: 'MAYG07', department: 'Mathematics', is_academic: true },
  { name: 'Geometry Honors', code: 'MAYG05', department: 'Mathematics', is_academic: true },
  { name: 'Geometry Applications in Engineering GAIN', code: 'MAYG03-ENG', department: 'Mathematics', is_academic: true },
  { name: 'Algebra 2', code: 'MAYA11', department: 'Mathematics', is_academic: true },
  { name: 'Algebra 2 Extension', code: 'MAYA11-E', department: 'Mathematics', is_academic: true },
  { name: 'Algebra 2 Advanced Honors', code: 'MAYA05', department: 'Mathematics', is_academic: true },
  { name: 'Algebra 2 Honors', code: 'MAYA07', department: 'Mathematics', is_academic: true },
  { name: 'Intermediate Algebra', code: 'MAYA20', department: 'Mathematics', is_academic: true },
  { name: 'Probability & Statistics Honors', code: 'MAYM22', department: 'Mathematics', is_academic: true },
  { name: 'Calculus Honors', code: 'MAYM07', department: 'Mathematics', is_academic: true },
  { name: 'AP Statistics', code: 'MAYM23', department: 'Mathematics', is_academic: true },
  { name: 'AP Precalculus M33', code: 'MAM33', department: 'Mathematics', is_academic: true },
  { name: 'AP Precalculus M44', code: 'MAM44', department: 'Mathematics', is_academic: true },
  { name: 'AP Calculus AB', code: 'MAYM09', department: 'Mathematics', is_academic: true },
  { name: 'AP Calculus BC', code: 'MAYM11', department: 'Mathematics', is_academic: true },
  { name: 'Post-Calculus Topics AP', code: 'MAYM16', department: 'Mathematics', is_academic: true },
  { name: 'Mathematical Modeling and Research AP', code: 'MAYM25', department: 'Mathematics', is_academic: true },
  { name: 'Math Extension', code: 'MASM03', department: 'Mathematics', is_academic: true },
  { name: 'Introduction to English Language Vocabulary', code: 'ENYX00', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'Introduction to English Language Grammar', code: 'ESYX00', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'Introduction to English Language Grammar Lab', code: 'ESYX00-L', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'Introduction to English Language Reading', code: 'RDYX00', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'English Learner Grammar 1', code: 'ESYX01', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'English Learner Literature 1', code: 'ENYX01', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'English Learner Reading 1', code: 'RDYX01', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'English Learner Grammar 2', code: 'ESYX02', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'English Learner Literature 2', code: 'ENYX02', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'English Learner Reading 2', code: 'RDYX03', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'English Learner Grammar 3', code: 'ESYX03', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'English Learner Literature 3', code: 'ENYX03', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'Freshman English ELL', code: 'ENYX19', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'Sophomore English ELL', code: 'ENYX29', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'American Studies — Literature and Composition ELL', code: 'ENYJ09', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'Social Justice and Equity ELL', code: 'ENYX40', department: 'Multilingual Learners — English', is_academic: true },
  { name: 'Algebra 1 ELL', code: 'MAYX20', department: 'Multilingual Learners — Other', is_academic: true },
  { name: 'Geometry ELL', code: 'MAYX30', department: 'Multilingual Learners — Other', is_academic: true },
  { name: 'Algebra 2 ELL', code: 'MAYX40', department: 'Multilingual Learners — Other', is_academic: true },
  { name: 'AP Precalculus ELL', code: 'MAX50', department: 'Multilingual Learners — Other', is_academic: true },
  { name: 'Math Extension ELL', code: 'MASX03', department: 'Multilingual Learners — Other', is_academic: true },
  { name: 'Physical Science ELL', code: 'SCYX01', department: 'Multilingual Learners — Other', is_academic: true },
  { name: 'Biology ELL', code: 'SCYX03', department: 'Multilingual Learners — Other', is_academic: true },
  { name: 'Intro to Social Studies 1 ELL', code: 'SOYX03', department: 'Multilingual Learners — Other', is_academic: true },
  { name: 'Modern World History ELL', code: 'SOYX02', department: 'Multilingual Learners — Other', is_academic: true },
  { name: 'Civics ELL', code: 'SOSX08', department: 'Multilingual Learners — Other', is_academic: true },
  { name: 'American Studies — US History ELL', code: 'SOYX01', department: 'Multilingual Learners — Other', is_academic: true },
  { name: 'Freshman Foundations', code: 'PBYB01', department: 'Physical Welfare', is_academic: false },
  { name: 'Driver Education', code: 'DESD01', department: 'Physical Welfare', is_academic: false },
  { name: 'Physical Education — Adapted', code: 'PEYN01', department: 'Physical Welfare', is_academic: false },
  { name: 'Sophomore PE with Health', code: 'PEYS05', department: 'Physical Welfare', is_academic: false },
  { name: 'Aerobics', code: 'PESR01', department: 'Physical Welfare', is_academic: false },
  { name: 'PE Leaders 2 — Juniors', code: 'PEYL02', department: 'Physical Welfare', is_academic: false },
  { name: 'PE Leaders 3 — Seniors', code: 'PEYL03', department: 'Physical Welfare', is_academic: false },
  { name: 'Adventure Education 1', code: 'PESA01', department: 'Physical Welfare', is_academic: false },
  { name: 'Adventure Education 2', code: 'PESA02', department: 'Physical Welfare', is_academic: false },
  { name: 'Dance Foundations', code: null, department: 'Physical Welfare', is_academic: false },
  { name: 'Advanced Dance', code: null, department: 'Physical Welfare', is_academic: false },
  { name: 'Integrated Physical Education', code: 'PEYV01', department: 'Physical Welfare', is_academic: false },
  { name: 'Sports Fitness', code: 'PESR02', department: 'Physical Welfare', is_academic: false },
  { name: 'Strength & Conditioning', code: 'PESW01', department: 'Physical Welfare', is_academic: false },
  { name: 'Varsity Physical Education', code: 'PEYW03', department: 'Physical Welfare', is_academic: false },
  { name: 'Exploratory Chemistry & Physics', code: 'SCYD02', department: 'Science', is_academic: true },
  { name: 'Biology', code: 'SCYB03', department: 'Science', is_academic: true },
  { name: 'Biology Honors', code: 'SCYB05', department: 'Science', is_academic: true },
  { name: 'Chemistry', code: 'SCYC03', department: 'Science', is_academic: true },
  { name: 'Chemistry Honors', code: 'SCYC05', department: 'Science', is_academic: true },
  { name: 'Conceptual Chemistry', code: 'SCYC01', department: 'Science', is_academic: true },
  { name: 'Conceptual Physics', code: 'SCYP09', department: 'Science', is_academic: true },
  { name: 'Physics', code: 'SCYP01', department: 'Science', is_academic: true },
  { name: 'Science Topics', code: 'SCYT01', department: 'Science', is_academic: true },
  { name: 'AP Biology', code: 'SCYB09', department: 'Science', is_academic: true },
  { name: 'AP Chemistry', code: 'SCYC07', department: 'Science', is_academic: true },
  { name: 'AP Physics 1', code: 'SCYP06', department: 'Science', is_academic: true },
  { name: 'AP Physics C', code: 'SCYP05', department: 'Science', is_academic: true },
  { name: 'STEM Inquiry and Research AP', code: 'SCYT05', department: 'Science', is_academic: true },
  { name: 'AP Environmental Science / Dual Credit', code: 'SCYE27', department: 'Science', is_academic: true },
  { name: 'Anatomy and Physiology', code: 'SCYP07', department: 'Science', is_academic: true },
  { name: 'Astronomy and Modern Physics Honors', code: 'SCYP04', department: 'Science', is_academic: true },
  { name: 'Forensic Science', code: 'SCYF01', department: 'Science', is_academic: true },
  { name: 'Health Careers / Medical Terminology Honors / Dual Credit', code: 'SCYM03', department: 'Science', is_academic: true },
  { name: 'Zoology', code: 'SCYG01', department: 'Science', is_academic: true },
  { name: 'Basic Nurse Assistant / Dual Credit', code: 'SCYM10', department: 'Science', is_academic: true },
  { name: 'Modern World History', code: 'SOYW01', department: 'Social Studies', is_academic: true },
  { name: 'AP World History', code: 'SOYW07', department: 'Social Studies', is_academic: true },
  { name: 'Civics', code: 'SOSC08', department: 'Social Studies', is_academic: true },
  { name: 'AP Government and Politics', code: 'SOYP12', department: 'Social Studies', is_academic: true },
  { name: 'American Studies — US History', code: 'SOYU09', department: 'Social Studies', is_academic: true },
  { name: 'United States History Honors', code: 'SOYU05', department: 'Social Studies', is_academic: true },
  { name: 'AP United States History', code: 'SOYU07', department: 'Social Studies', is_academic: true },
  { name: 'Intro to Debate', code: 'SOSD03', department: 'Social Studies', is_academic: true },
  { name: 'Debate Honors', code: 'SOYD01', department: 'Social Studies', is_academic: true },
  { name: 'Advanced Debate Honors', code: 'SOYD05', department: 'Social Studies', is_academic: true },
  { name: 'Asian American Studies — History', code: 'SOSA02', department: 'Social Studies', is_academic: true },
  { name: 'Black and LatinX Studies', code: 'SOSA01', department: 'Social Studies', is_academic: true },
  { name: 'Global Problems', code: 'SOSG01', department: 'Social Studies', is_academic: true },
  { name: 'Law', code: 'SOSL01', department: 'Social Studies', is_academic: true },
  { name: 'Psychology', code: 'SOSP07', department: 'Social Studies', is_academic: true },
  { name: 'Sociology', code: 'SOSS01', department: 'Social Studies', is_academic: true },
  { name: 'World Religions', code: 'SOSR01', department: 'Social Studies', is_academic: true },
  { name: 'World War II', code: 'SOSW02', department: 'Social Studies', is_academic: true },
  { name: 'AP Economics', code: 'SOSE07', department: 'Social Studies', is_academic: true },
  { name: 'AP European History', code: 'SOYE03', department: 'Social Studies', is_academic: true },
  { name: 'AP Psychology', code: 'SOYP07', department: 'Social Studies', is_academic: true },
  { name: 'Freshman English SpEd', code: 'ENYY51', department: 'SpEd — English', is_academic: true },
  { name: 'Freshman English with Reading SpEd', code: 'ENYV01', department: 'SpEd — English', is_academic: true },
  { name: 'Sophomore English SpEd', code: 'ENYY53', department: 'SpEd — English', is_academic: true },
  { name: 'Sophomore English with Reading SpEd', code: 'ENYV03', department: 'SpEd — English', is_academic: true },
  { name: 'American Literature and Composition SpEd', code: 'ENYY55', department: 'SpEd — English', is_academic: true },
  { name: 'Junior English with Reading SpEd', code: 'ENYN05', department: 'SpEd — English', is_academic: true },
  { name: 'Senior English SpEd', code: 'ENYY57', department: 'SpEd — English', is_academic: true },
  { name: 'Senior English with Reading SpEd', code: 'ENYV07', department: 'SpEd — English', is_academic: true },
  { name: 'Algebra 1-2 SpEd', code: 'MAYY03', department: 'SpEd — Mathematics', is_academic: true },
  { name: 'Math with Algebra 1-2 SpEd', code: 'MAYV01', department: 'SpEd — Mathematics', is_academic: true },
  { name: 'Geometry 1-2 SpEd', code: 'MAYY07', department: 'SpEd — Mathematics', is_academic: true },
  { name: 'Math with Geometry 3-4 SpEd', code: 'MAYV03', department: 'SpEd — Mathematics', is_academic: true },
  { name: 'Algebra 3-4 SpEd', code: 'MAYY13', department: 'SpEd — Mathematics', is_academic: true },
  { name: 'Math with Algebra 5-6 SpEd', code: 'MAYV05', department: 'SpEd — Mathematics', is_academic: true },
  { name: 'Applied Math 7-8 SpEd', code: 'MAYN07', department: 'SpEd — Mathematics', is_academic: true },
  { name: 'Biology SpEd', code: 'SCYY10', department: 'SpEd — Science', is_academic: true },
  { name: 'Life Skills Science SpEd', code: 'SCYV01', department: 'SpEd — Science', is_academic: true },
  { name: 'Physical Science SpEd', code: 'SCYY12', department: 'SpEd — Science', is_academic: true },
  { name: 'Community Studies SpEd', code: 'SOYV10', department: 'SpEd — Social Studies', is_academic: true },
  { name: 'Modern World History SpEd', code: 'SOYY16', department: 'SpEd — Social Studies', is_academic: true },
  { name: 'Vocational Awareness SpEd', code: 'BUYV32', department: 'SpEd — Social Studies', is_academic: true },
  { name: 'Civics SpEd', code: 'SOSY08', department: 'SpEd — Social Studies', is_academic: true },
  { name: 'United States History SpEd', code: 'SOYY14', department: 'SpEd — Social Studies', is_academic: true },
  { name: 'Law SpEd', code: 'SOYQ13', department: 'SpEd — Social Studies', is_academic: true },
  { name: 'Work Study Classroom SpEd', code: 'CVYY10', department: 'SpEd — Work Study', is_academic: false },
  { name: 'Work Study on the Job SpEd', code: 'CVYY14', department: 'SpEd — Work Study', is_academic: false },
  { name: 'Assyrian 1 Language and Culture', code: 'LAYA01', department: 'World Languages — Assyrian', is_academic: true },
  { name: 'Assyrian 1 Language and Culture Honors', code: 'LAYA03', department: 'World Languages — Assyrian', is_academic: true },
  { name: 'Assyrian 2 Language and Culture', code: 'LAYA05', department: 'World Languages — Assyrian', is_academic: true },
  { name: 'Assyrian 2 Language and Culture Honors', code: 'LAYA07', department: 'World Languages — Assyrian', is_academic: true },
  { name: 'Assyrian 3 Language and Culture', code: null, department: 'World Languages — Assyrian', is_academic: true },
  { name: 'Assyrian 3 Language and Culture Honors', code: null, department: 'World Languages — Assyrian', is_academic: true },
  { name: 'Assyrian for Heritage Speakers', code: 'LAYA27', department: 'World Languages — Assyrian', is_academic: true },
  { name: 'Assyrian for Heritage Speakers Honors', code: 'LAYA29', department: 'World Languages — Assyrian', is_academic: true },
  { name: 'Chinese 1 Language and Culture', code: 'LAYC01', department: 'World Languages — Chinese', is_academic: true },
  { name: 'Chinese 2 Language and Culture', code: 'LAYC03', department: 'World Languages — Chinese', is_academic: true },
  { name: 'Chinese 2 Language and Culture Honors', code: 'LAYC05', department: 'World Languages — Chinese', is_academic: true },
  { name: 'Chinese 3 Language and Culture', code: 'LAYC07', department: 'World Languages — Chinese', is_academic: true },
  { name: 'Chinese 3 Language and Culture Honors', code: 'LAYC09', department: 'World Languages — Chinese', is_academic: true },
  { name: 'Chinese 4 Language and Culture', code: 'LAYC11', department: 'World Languages — Chinese', is_academic: true },
  { name: 'Chinese 4 Language and Culture Honors', code: 'LAYC13', department: 'World Languages — Chinese', is_academic: true },
  { name: 'Chinese AP Language and Culture', code: 'LAYC15', department: 'World Languages — Chinese', is_academic: true },
  { name: 'French 1 Language and Culture', code: 'LAYF01', department: 'World Languages — French', is_academic: true },
  { name: 'French 1 Language and Culture Honors', code: 'LAYF03', department: 'World Languages — French', is_academic: true },
  { name: 'French 2 Language and Culture', code: 'LAYF05', department: 'World Languages — French', is_academic: true },
  { name: 'French 2 Language and Culture Honors', code: 'LAYF07', department: 'World Languages — French', is_academic: true },
  { name: 'French 3 Language and Culture', code: 'LAYF09', department: 'World Languages — French', is_academic: true },
  { name: 'French 3 Language and Culture Honors', code: 'LAYF11', department: 'World Languages — French', is_academic: true },
  { name: 'French 4 Language and Culture', code: 'LAYF13', department: 'World Languages — French', is_academic: true },
  { name: 'French 4 Language and Culture Honors', code: 'LAYF15', department: 'World Languages — French', is_academic: true },
  { name: 'French 4 AP Language and Culture', code: 'LAYF23', department: 'World Languages — French', is_academic: true },
  { name: 'German 1 Language and Culture', code: 'LAYG01', department: 'World Languages — German', is_academic: true },
  { name: 'German 1 Language and Culture Honors', code: 'LAYG03', department: 'World Languages — German', is_academic: true },
  { name: 'German 2 Language and Culture', code: 'LAYG05', department: 'World Languages — German', is_academic: true },
  { name: 'German 2 Language and Culture Honors', code: 'LAYG07', department: 'World Languages — German', is_academic: true },
  { name: 'German 3 Language and Culture', code: 'LAYG09', department: 'World Languages — German', is_academic: true },
  { name: 'German 3 Language and Culture Honors', code: 'LAYG11', department: 'World Languages — German', is_academic: true },
  { name: 'German 4 Language and Culture', code: 'LAYG13', department: 'World Languages — German', is_academic: true },
  { name: 'German 4 Language and Culture Honors', code: 'LAYG15', department: 'World Languages — German', is_academic: true },
  { name: 'German 4 AP Language and Culture', code: 'LAYG21', department: 'World Languages — German', is_academic: true },
  { name: 'Hebrew 1', code: 'LAYH01', department: 'World Languages — Hebrew', is_academic: true },
  { name: 'Hebrew 2', code: 'LAYH03', department: 'World Languages — Hebrew', is_academic: true },
  { name: 'Hebrew 2 Honors', code: 'LAYH09', department: 'World Languages — Hebrew', is_academic: true },
  { name: 'Hebrew 3', code: 'LAYH05', department: 'World Languages — Hebrew', is_academic: true },
  { name: 'Hebrew 3 Honors', code: 'LAYH11', department: 'World Languages — Hebrew', is_academic: true },
  { name: 'Hebrew 4 / Dual Credit', code: 'LAYH07', department: 'World Languages — Hebrew', is_academic: true },
  { name: 'Hebrew 4 Honors / Dual Credit', code: 'LAYH13', department: 'World Languages — Hebrew', is_academic: true },
  { name: 'Advanced Hebrew Topics Honors / Dual Credit', code: 'LAYH17', department: 'World Languages — Hebrew', is_academic: true },
  { name: 'Spanish Introduction 1', code: 'LAYS01', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish 1', code: 'LAYS03', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish for Heritage Speakers', code: 'LAYS27', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish for Heritage Speakers Honors', code: 'LAYS29', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish Introduction 2', code: 'LAYS07', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish 2', code: 'LAYS09', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish 2 Honors', code: 'LAYS11', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish 3', code: 'LAYS13', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish 3 Honors', code: 'LAYS15', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish 4', code: 'LAYS17', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish 4 Honors', code: 'LAYS19', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish Conversation Honors', code: 'LAYS21', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Advanced Spanish for Heritage Speakers', code: 'LAYS33', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Advanced Spanish for Heritage Speakers Honors', code: 'LAYS35', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Spanish AP Language and Culture', code: 'LAYS25', department: 'World Languages — Spanish', is_academic: true },
  { name: 'AP Spanish Literature and Culture', code: 'LAYS31', department: 'World Languages — Spanish', is_academic: true },
  { name: 'Advanced Spanish Topics AP', code: 'LAYS23', department: 'World Languages — Spanish', is_academic: true }
];

window.aceCourseCatalogHelpers = {
  byDepartment() {
    const groups = {};
    window.aceCourseCatalog.forEach(c => {
      if (!groups[c.department]) groups[c.department] = [];
      groups[c.department].push(c);
    });
    return groups;
  },
  findByCode(code) {
    return window.aceCourseCatalog.find(c => c.code === code) || null;
  },
  findByName(name) {
    return window.aceCourseCatalog.find(c => c.name === name) || null;
  }
};
